# Integrantes: [Sofia Aviles Diaz], [Santiafo Barrero Lopez], [Yvette Daniela Campo Osorio]

defmodule Datos do
  @moduledoc """
  Datos del grupo para el Parcial 1 (empresa de mensajería).
  """

  def repartidores do
    [
      %{codigo: "M01", nombre: "Ana Torres", bicicleta: true},
      %{codigo: "M02", nombre: "David López", bicicleta: false},
      %{codigo: "M03", nombre: "Camila Ríos", bicicleta: true},
      %{codigo: "M04", nombre: "Sebastián Gómez", bicicleta: false},
      %{codigo: "M05", nombre: "Valentina Cruz", bicicleta: true},
      %{codigo: "M06", nombre: "Juan Pablo Mejía", bicicleta: false},
      %{codigo: "M07", nombre: "Laura Ospina", bicicleta: true},
      %{codigo: "M08", nombre: "Andrés Cardona", bicicleta: false},
      %{codigo: "M09", nombre: "Mariana Salazar", bicicleta: true},
      %{codigo: "M10", nombre: "Felipe Duque", bicicleta: false},
      %{codigo: "M11", nombre: "Daniela Marín", bicicleta: false},
      %{codigo: "M12", nombre: "Camilo Restrepo", bicicleta: false}
    ]
  end

  def zonas do
    [
      %{id: "Z1", nombre: "Centro", area: 6.5},
      %{id: "Z2", nombre: "Norte", area: 10.2},
      %{id: "Z3", nombre: "Sur", area: 8.4},
      %{id: "Z4", nombre: "Occidente", area: 12.8}
    ]
  end

  def servicios do
    [
      %{repartidor: "M02", zona: "Z2", dia: 4, kilometros: 34, retraso: 2},
      %{repartidor: "M10", zona: "Z1", dia: 2, kilometros: 26, retraso: 6},
      %{repartidor: "M02", zona: "Z1", dia: 1, kilometros: 16.4, retraso: -8},
      %{repartidor: "M04", zona: "Z1", dia: 4, kilometros: 22, retraso: 37},
      %{repartidor: "M01", zona: "Z4", dia: 3, kilometros: 8.3, retraso: 23},
      %{repartidor: "M08", zona: "Z2", dia: 1, kilometros: 5, retraso: 48},
      %{repartidor: "M10", zona: "Z3", dia: 3, kilometros: 7.2, retraso: -20},
      %{repartidor: "M10", zona: "Z3", dia: 2, kilometros: 5, retraso: 6},
      %{repartidor: "M03", zona: "Z3", dia: 5, kilometros: 38, retraso: 8},
      %{repartidor: "M08", zona: "Z2", dia: 4, kilometros: 30, retraso: 1},
      %{repartidor: "M03", zona: "Z1", dia: 0, kilometros: 14, retraso: 3},
      %{repartidor: "M07", zona: "Z2", dia: 5, kilometros: 45.5, retraso: 8},
      %{repartidor: "M08", zona: "Z3", dia: 1, kilometros: 20.9, retraso: 64},
      %{repartidor: "M01", zona: "Z4", dia: 6, kilometros: 4.5, retraso: 26},
      %{repartidor: "M06", zona: "Z4", dia: 1, kilometros: 32, retraso: 10},
      %{repartidor: "M05", zona: "Z4", dia: 3, kilometros: 15.7, retraso: 21},
      %{repartidor: "M09", zona: "Z2", dia: 3, kilometros: 27.1, retraso: 33},
      %{repartidor: "M06", zona: "Z2", dia: 6, kilometros: 9, retraso: "tarde"},
      %{repartidor: "M11", zona: "Z3", dia: 3, kilometros: 15, retraso: -25},
      %{repartidor: "M01", zona: "Z1", dia: 3, kilometros: 15.8, retraso: 18},
      %{repartidor: "M05", zona: "Z2", dia: 5, kilometros: 15.8, retraso: 9},
      %{repartidor: "M10", zona: "Z4", dia: 5, kilometros: 5.2, retraso: 44},
      %{repartidor: "M07", zona: "Z1", dia: 1, kilometros: 6, retraso: 9},
      %{repartidor: "M06", zona: "Z1", dia: 2, kilometros: 29.7, retraso: 4},
      %{repartidor: "M10", zona: "Z2", dia: 4, kilometros: 38, retraso: -19},
      %{repartidor: "M10", zona: "Z4", dia: 2, kilometros: 60, retraso: 999},
      %{repartidor: "M06", zona: "Z3", dia: 3, kilometros: 8.5, retraso: 17},
      %{repartidor: "M04", zona: "Z1", dia: 2, kilometros: 21.8, retraso: 53},
      %{repartidor: "M03", zona: "Z3", dia: 3, kilometros: 25, retraso: 71},
      %{repartidor: "M01", zona: "Z4", dia: 6, kilometros: 24, retraso: 67},
      %{repartidor: "M01", zona: "Z1", dia: 2, kilometros: 12, retraso: -4},
      %{repartidor: "M07", zona: "Z1", dia: 5, kilometros: 5, retraso: 14},
      %{repartidor: "M09", zona: "Z1", dia: 3, kilometros: 13, retraso: 16},
      %{repartidor: "M09", zona: "Z1", dia: 1, kilometros: 21.9, retraso: 36},
      %{repartidor: "M04", zona: "Z1", dia: 5, kilometros: 4, retraso: -13},
      %{repartidor: "M08", zona: "Z4", dia: 5, kilometros: 37, retraso: -13},
      %{repartidor: "M07", zona: "Z4", dia: 1, kilometros: 11.0, retraso: 66},
      %{repartidor: "M10", zona: "Z2", dia: 4, kilometros: 20, retraso: 1},
      %{repartidor: "M06", zona: "Z4", dia: 5, kilometros: 14, retraso: 12},
      %{repartidor: "M04", zona: "Z4", dia: 3, kilometros: 26, retraso: 19},
      %{repartidor: "M04", zona: "Z2", dia: 5, kilometros: 14.1, retraso: 10},
      %{repartidor: "M03", zona: "Z2", dia: 4, kilometros: 35, retraso: 60},
      %{repartidor: "M08", zona: "Z1", dia: 4, kilometros: 13.1, retraso: -12},
      %{repartidor: "M03", zona: "Z3", dia: 2, kilometros: 22, retraso: -7},
      %{repartidor: "M09", zona: "Z4", dia: 6, kilometros: 24, retraso: 6},
      %{repartidor: "M09", zona: "Z1", dia: 3, kilometros: 18.1, retraso: -11},
      %{repartidor: "M01", zona: "Z2", dia: 1, kilometros: 24, retraso: 57},
      %{repartidor: "M01", zona: "Z4", dia: 2, kilometros: 18.0, retraso: -20},
      %{repartidor: "M03", zona: "Z4", dia: 6, kilometros: 5.7, retraso: -17},
      %{repartidor: "M06", zona: "Z1", dia: 1, kilometros: 32.3, retraso: 26},
      %{repartidor: "M05", zona: "Z2", dia: 1, kilometros: 38, retraso: 30},
      %{repartidor: "M09", zona: "Z2", dia: 6, kilometros: 9, retraso: -10},
      %{repartidor: "M05", zona: "Z4", dia: 1, kilometros: 9.3, retraso: 9},
      %{repartidor: "M10", zona: "Z2", dia: 1, kilometros: 7.3, retraso: 1},
      %{repartidor: "M05", zona: "Z2", dia: 1, kilometros: 13.9, retraso: 63},
      %{repartidor: "M09", zona: "Z1", dia: 5, kilometros: 30.4, retraso: -13},
      %{repartidor: "M07", zona: "Z4", dia: 5, kilometros: 20.7, retraso: 27},
      %{repartidor: "M10", zona: "Z3", dia: 6, kilometros: 24, retraso: 8},
      %{repartidor: "M08", zona: "Z4", dia: 1, kilometros: 38, retraso: 22},
      %{repartidor: "M07", zona: "Z4", dia: 2, kilometros: 19.6, retraso: 41},
      %{repartidor: "M99", zona: "Z1", dia: 1, kilometros: 10, retraso: 2},
      %{repartidor: "X01", zona: "Z2", dia: 3, kilometros: 15, retraso: 0},
      %{repartidor: "M09", zona: "Z1", dia: 5, kilometros: 31, retraso: 30},
      %{repartidor: "M02", zona: "Z1", dia: 4, kilometros: 29.1, retraso: 25},
      %{repartidor: "M10", zona: "Z2", dia: 3, kilometros: 31, retraso: 26},
      %{repartidor: "M02", zona: "Z3", dia: 2, kilometros: 7.2, retraso: 33},
      %{repartidor: "M07", zona: "Z3", dia: 4, kilometros: 21, retraso: -1},
      %{repartidor: "M04", zona: "Z2", dia: 4, kilometros: 33, retraso: 37},
      %{repartidor: "M08", zona: "Z1", dia: 5, kilometros: 9.1, retraso: -3},
      %{repartidor: "M04", zona: "Z3", dia: 3, kilometros: 26.5, retraso: 25},
      %{repartidor: "M04", zona: "Z1", dia: 6, kilometros: 35, retraso: 12},
      %{repartidor: "M09", zona: "Z3", dia: 3, kilometros: "12", retraso: 5},
      %{repartidor: "M06", zona: "Z3", dia: 5, kilometros: 31.2, retraso: 28},
      %{repartidor: "M04", zona: "Z4", dia: 3, kilometros: 15.4, retraso: 6},
      %{repartidor: "M04", zona: "Z2", dia: 7, kilometros: 22, retraso: 6},
      %{repartidor: "M04", zona: "Z4", dia: 5, kilometros: 37.6, retraso: -13},
      %{repartidor: "M02", zona: "Z3", dia: 1, kilometros: 11.1, retraso: -9},
      %{repartidor: "M04", zona: "Z4", dia: 1, kilometros: 30.1, retraso: 51},
      %{repartidor: "M08", zona: "Z3", dia: "3", kilometros: 18, retraso: 2},
      %{repartidor: "M05", zona: "Z3", dia: 6, kilometros: 7, retraso: 69},
      %{repartidor: "M01", zona: "Z1", dia: 3, kilometros: 35.2, retraso: 26},
      %{repartidor: "M09", zona: "Z2", dia: 2, kilometros: 36.5, retraso: 40},
      %{repartidor: "M07", zona: "Z4", dia: 3, kilometros: 27.2, retraso: 27},
      %{repartidor: "M08", zona: "Z2", dia: 3, kilometros: 37.9, retraso: 10},
      %{repartidor: "M05", zona: "Z4", dia: 5, kilometros: 8.4, retraso: 50},
      %{repartidor: "M07", zona: "Z4", dia: 4, kilometros: 17, retraso: 18},
      %{repartidor: "M77", zona: "Z9", dia: 9, kilometros: 99, retraso: 500},
      %{repartidor: "M05", zona: "Z1", dia: 5, kilometros: 16, retraso: -45},
      %{repartidor: "M01", zona: "Z3", dia: 5, kilometros: 34, retraso: 8},
      %{repartidor: "M09", zona: "Z2", dia: 2, kilometros: 22.4, retraso: 85},
      %{repartidor: "M08", zona: "Z2", dia: 2, kilometros: 16.7, retraso: 28},
      %{repartidor: "M01", zona: "Z2", dia: 5, kilometros: 15, retraso: 6},
      %{repartidor: "M03", zona: "Z1", dia: 1, kilometros: 34, retraso: 26},
      %{repartidor: "M02", zona: "Z2", dia: 3, kilometros: 32.3, retraso: 8},
      %{repartidor: "M05", zona: "Z3", dia: 3, kilometros: 17, retraso: 10},
      %{repartidor: "M09", zona: "Z1", dia: 4, kilometros: 16.1, retraso: -14},
      %{repartidor: "M11", zona: "Z1", dia: 1, kilometros: 10, retraso: -20},
      %{repartidor: "M04", zona: "Z4", dia: 6, kilometros: 25, retraso: 0},
      %{repartidor: "M02", zona: "Z4", dia: 1, kilometros: 21.2, retraso: 67},
      %{repartidor: "M08", zona: "Z3", dia: 2, kilometros: 11, retraso: nil},
      %{repartidor: "M10", zona: "Z1", dia: 1, kilometros: 21.2, retraso: 16},
      %{repartidor: "M10", zona: "Z3", dia: 5, kilometros: 16.2, retraso: -11},
      %{repartidor: "M09", zona: "Z2", dia: 5, kilometros: 37.9, retraso: 2},
      %{repartidor: "M07", zona: "Z3", dia: 2, kilometros: 13, retraso: 7},
      %{repartidor: "M06", zona: "Z4", dia: 4, kilometros: 28.4, retraso: 6},
      %{repartidor: "M01", zona: "Z2", dia: 3, kilometros: 20, retraso: 27},
      %{repartidor: "M10", zona: "Z2", dia: 5, kilometros: 14.9, retraso: 64},
      %{repartidor: "M05", zona: "Z1", dia: 3, kilometros: 5.0, retraso: 45},
      %{repartidor: "M03", zona: "Z1", dia: 2, kilometros: 36.2, retraso: 20},
      %{repartidor: "M01", zona: "Z3", dia: 2, kilometros: 12, retraso: -4},
      %{repartidor: "M02", zona: "Z4", dia: 5, kilometros: 7.0, retraso: -2},
      %{repartidor: "M02", zona: "Z2", dia: 4, kilometros: 9.9, retraso: 28},
      %{repartidor: "M02", zona: "Z1", dia: 5, kilometros: 5, retraso: 4},
      %{repartidor: "M02", zona: "Z9", dia: 2, kilometros: 12, retraso: 4},
      %{repartidor: "M06", zona: "Z4", dia: 5, kilometros: 15.9, retraso: 57},
      %{repartidor: "M08", zona: "Z2", dia: 5, kilometros: 34.3, retraso: -6},
      %{repartidor: "M02", zona: "Z3", dia: 1, kilometros: 7.0, retraso: -6},
      %{repartidor: "M01", zona: "Z1", dia: 1, kilometros: 32, retraso: 31},
      %{repartidor: "M08", zona: "Z1", dia: 3, kilometros: 21.7, retraso: 4},
      %{repartidor: "M04", zona: "Z4", dia: 5, kilometros: 36.4, retraso: 78},
      %{repartidor: "M03", zona: "Z3", dia: 4, kilometros: 35.6, retraso: -18},
      %{repartidor: "M03", zona: "Z4", dia: 4, kilometros: 10, retraso: 200},
      %{repartidor: "M09", zona: "Z1", dia: 1, kilometros: 25, retraso: 3},
      %{repartidor: "M04", zona: "Z4", dia: 1, kilometros: 18.9, retraso: 26},
      %{repartidor: "M02", zona: "Z3", dia: 3, kilometros: 31, retraso: 19},
      %{repartidor: "M09", zona: "Z2", dia: 4, kilometros: 26.2, retraso: -20},
      %{repartidor: "M06", zona: "Z8", dia: 0, kilometros: 0, retraso: 0},
      %{repartidor: "M05", zona: "Z3", dia: 2, kilometros: 13, retraso: 24},
      %{repartidor: "M08", zona: "Z1", dia: 6, kilometros: 10.6, retraso: -9},
      %{repartidor: "M03", zona: "Z2", dia: 1, kilometros: 37, retraso: 76},
      %{repartidor: "M05", zona: "Z0", dia: 4, kilometros: 20, retraso: 1},
      %{repartidor: "M03", zona: "Z1", dia: 5, kilometros: 17.9, retraso: 40},
      %{repartidor: "M06", zona: "Z4", dia: 4, kilometros: 32, retraso: -2},
      %{repartidor: "M02", zona: "Z2", dia: 6, kilometros: 30, retraso: 5},
      %{repartidor: "M06", zona: "Z4", dia: 6, kilometros: 19.4, retraso: -6},
      %{repartidor: "M04", zona: "Z2", dia: 2, kilometros: 16.8, retraso: 32},
      %{repartidor: "M06", zona: "Z3", dia: 2, kilometros: 33.3, retraso: 9},
      %{repartidor: "M05", zona: "Z1", dia: 3, kilometros: 27, retraso: 45},
      %{repartidor: "M03", zona: "Z4", dia: 1, kilometros: 5.1, retraso: 75},
      %{repartidor: "M10", zona: "Z3", dia: 5, kilometros: 24.4, retraso: 56},
      %{repartidor: "M03", zona: "Z4", dia: 5, kilometros: 34, retraso: 15},
      %{repartidor: "M05", zona: "Z1", dia: 4, kilometros: 22.2, retraso: -19},
      %{repartidor: "M09", zona: "Z4", dia: 5, kilometros: 33, retraso: 25},
      %{repartidor: "M06", zona: "Z3", dia: 3, kilometros: 32.6, retraso: 83},
      %{repartidor: "M02", zona: "Z4", dia: 2, kilometros: 24.7, retraso: 27},
      %{repartidor: "M01", zona: "Z4", dia: 2, kilometros: 12, retraso: -4},
      %{repartidor: "M02", zona: "Z2", dia: 3, kilometros: 35, retraso: 22},
      %{repartidor: "M09", zona: "Z2", dia: 1, kilometros: 25.1, retraso: 5},
      %{repartidor: "M01", zona: "Z1", dia: 5, kilometros: 7.1, retraso: 10},
      %{repartidor: "M07", zona: "Z4", dia: 5, kilometros: 27, retraso: 1},
      %{repartidor: "M07", zona: "Z3", dia: 3, kilometros: 14.8, retraso: 2},
      %{repartidor: "M05", zona: "Z2", dia: 2, kilometros: 12, retraso: 27},
      %{repartidor: "M01", zona: "Z4", dia: 4, kilometros: 37.7, retraso: 50},
      %{repartidor: "M03", zona: "Z4", dia: 1, kilometros: 26.8, retraso: 17},
      %{repartidor: "M02", zona: "Z3", dia: 6, kilometros: 30, retraso: -2},
      %{repartidor: "M08", zona: "Z2", dia: 3, kilometros: 17, retraso: 15},
      %{repartidor: "M03", zona: "Z4", dia: 3, kilometros: 4.7, retraso: 2},
      %{repartidor: "M06", zona: "Z4", dia: 4, kilometros: 12.1, retraso: 8},
      %{repartidor: "M01", zona: "Z2", dia: 2, kilometros: 12, retraso: -4},
      %{repartidor: "M04", zona: "Z4", dia: 1, kilometros: 35, retraso: -16},
      %{repartidor: "M07", zona: "Z2", dia: 6, kilometros: 10.5, retraso: 16},
      %{repartidor: "M09", zona: "Z4", dia: 3, kilometros: 38, retraso: 3},
      %{repartidor: "M04", zona: "Z1", dia: 2, kilometros: 25, retraso: -15},
      %{repartidor: "M06", zona: "Z4", dia: 1, kilometros: 13, retraso: -20},
      %{repartidor: "M08", zona: "Z3", dia: 5, kilometros: 33.7, retraso: 14},
      %{repartidor: "M08", zona: "Z2", dia: 4, kilometros: 27, retraso: -6},
      %{repartidor: "M09", zona: "Z1", dia: 2, kilometros: 22.6, retraso: 16},
      %{repartidor: "M01", zona: "Z1", dia: 1, kilometros: 0, retraso: 3}
    ]
  end
end
